# Generated by Django 2.1.5 on 2020-09-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('device_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manageapp.Product')),
                ('input_date', models.DateField()),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'input',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manageapp.Product')),
                ('output_date', models.DateField()),
                ('out_loc', models.CharField(blank=True, max_length=8, null=True)),
                ('cus_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'output',
            },
        ),
    ]
