# Generated by Django 2.1.5 on 2020-09-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0003_auto_20200923_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manageapp.Product'),
        ),
        migrations.AlterField(
            model_name='output',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manageapp.Product'),
        ),
    ]
